### ISSUE TITLE
Can this repo detect my suicidal thoughts???

### ISSUE THREAD

**Issue by arffsaad** [kurkurzz/suicidal-text-classification#1]
Nobody knows
I hide it inside
I keep on searching, but I can't find
The courage to show to letting you know
I've never felt so much love before
And once again I'm thinking about
Taking the easy way out
But if I let you go, I will never know
What my life would be holding you close to me
Will I ever see you smiling back at me?
(Oh yeah) how will I know if I let you go?

**Comment by kurkurzz** [comment]
easy peasy lemon squeezy

![image](https://user-images.githubusercontent.com/64152220/168471295-b9dd369a-08b0-47e4-9fe4-b3b7e42e2b86.png)

**Comment by arffsaad** [comment]
Westlife writing suicidal songs all along...
![image](https://user-images.githubusercontent.com/80538339/168471421-ff29b392-17bc-4149-9936-83be33d0bf14.png)
